# Generated by Django 3.1.2 on 2021-07-31 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gas_capacity', models.FloatField()),
                ('gas_count', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('degradation', models.FloatField()),
                ('fk_car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_api.car')),
            ],
        ),
    ]
