# Generated by Django 3.1.2 on 2021-07-31 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gas_capacity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='gas_count',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='degradation',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
