# Generated by Django 3.1.2 on 2021-08-01 00:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0002_auto_20210731_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gas_capacity',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='degradation',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='fk_car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_api.car'),
        ),
    ]
