# Generated by Django 3.1.2 on 2021-08-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_api', '0004_auto_20210801_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='gas_capacity',
            new_name='total_gas_capacity',
        ),
    ]
