# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f solution/api/requirements.txt ]; then pip install -r solution/api/requirements.txt; fi
        cd solution/api/
        ls
        
        # Install docker
        sudo apt-get update
        sudo apt install docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        docker --version
        
        # Docker compose install
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        
        
    - name: Test with pytest
      run: |
        # Run
        docker-compose up -d
        python manage.py test
